[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  NODE_ENV = "production"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  NODE_ENV = "production"